name: sound-pytorch-env
channels:
  - defaults
  - pytorch
  - conda-forge
dependencies:
  - python==3.8.5
  - cudatoolkit=10.1
  - torchaudio
  - pytorch
  - torchvision
  - scikit-learn
  - librosa
  - pip
  - pip:
    - comet-ml
    - torchsummary